# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: 'cn_test'

steps:
- task: AzureFileCopy@4
  inputs:
    sourcePath: $(storageAccount)$(containerObject)$(sasToken)
    azureSubscription: $(subscription)
    destination: AzureVMs
    storage: 
    resourceGroup: ADO_POC # Required when destination == AzureVMs
    vmsAdminUserName: azureuser # Required when destination == AzureVMs
    vmsAdminPassword: $(vmsAdminPassword)# Required when destination == AzureVMs
    targetPath: $(TargetFolder) # Required when destination == AzureVMs
